---
output: word_document
---
Projection Comparisons
========================================================

```{r, echo=FALSE, results="hide", message=FALSE, warning=FALSE, error=FALSE}
load("C:/Users/zhaohexu/Dropbox/Ozone project/data/project_data.RData")
library(merTools)
st <- study

##### Historical projection

# standardize variables

st$sNOx <- st$NOx/sd(st$NOx, na.rm = TRUE)
st$sVOC <- st$VOC/sd(st$VOC, na.rm = TRUE)
st$stemp.max <- st$temp.max/sd(st$temp.max, na.rm = TRUE)
st$shumid <- st$hmdt/sd(st$hmdt, na.rm = TRUE)
st$sprcp <- st$prcp/sd(st$prcp, na.rm = TRUE)
st$ssolar <- st$solar/sd(st$solar, na.rm = TRUE)

st$stemp.max.s <- st$temp.max.s/sd(st$temp.max.s, na.rm = TRUE)
st$shumid.s <- st$humid.s/sd(st$humid.s, na.rm = TRUE)
st$sprcp.s <- st$prcp.s/sd(st$prcp.s, na.rm = TRUE)
st$ssolar.s.GSW <- st$solar.s.GSW/sd(st$solar.s.GSW, na.rm = TRUE)
st$ssolar.s.RGRND <- st$solar.s.RGRND/sd(st$solar.s.RGRND, na.rm = TRUE)

# transform variables

st$y <- sqrt(st$ozone)
st$N2 <- st$sNOx^2
st$Vl <- log(st$sVOC+1)

# projection by monitor

tmp.id <- unique(st$siteID)
ozone.obs.mean <- 0
ozone.obs.sd <- 0
ozone.obs.IQR <- 0

ozone.pred.mean.GSW <- 0
ozone.pred.sd.GSW <- 0
ozone.pred.IQR.GSW <- 0

ozone.pred.mean.RGRND <- 0
ozone.pred.sd.RGRND <- 0
ozone.pred.IQR.RGRND <- 0

for (iid in tmp.id){
  st.sub <- st[st$siteID == iid, ]
  fit0 <- lm(y~(sprcp+stemp.max+shumid)*sNOx+
               (ssolar+stemp.max+shumid)*N2+
               (ssolar+stemp.max+shumid)*(sNOx:Vl), data=st.sub)
  
  beta <- fit0$coef
  vcov <- vcov(fit0)
  beta.sim <- t(mvrnorm(10000, beta, vcov))
  
  # design matrix
  # (1) solar radiation GSW
  fit1 <- lm(y~(sprcp.s+stemp.max.s+shumid.s)*sNOx+
               (ssolar.s.GSW+stemp.max.s+shumid.s)*N2+
               (ssolar.s.GSW+stemp.max.s+shumid.s)*(sNOx:Vl), data=st.sub)
  x1 <- model.matrix(fit1)
  rownames(x1) <- NULL
  
  # (2) solar radiation RGRND
  fit2 <- lm(y~(sprcp.s+stemp.max.s+shumid.s)*sNOx+
               (ssolar.s.RGRND+stemp.max.s+shumid.s)*N2+
               (ssolar.s.RGRND+stemp.max.s+shumid.s)*(sNOx:Vl), data=st.sub)
  x2 <- model.matrix(fit2)
  rownames(x2) <- NULL
  
  # predicted ozone -- historical
  # (1) solar radiation GSW
  ozone.sim1 <- (x1 %*% beta.sim)^2
  ozone.mean1 <- colMeans(ozone.sim1, na.rm = TRUE)
  
  ozone.pred.mean.GSW[iid] <- mean(ozone.mean1, na.rm = TRUE)
  ozone.pred.sd.GSW[iid] <- sd(ozone.mean1, na.rm = TRUE)
  ozone.pred.IQR.GSW[iid] <- IQR(ozone.mean1, na.rm = TRUE)
  
  # (2) solar radiation RGRND
  ozone.sim2 <- (x2 %*% beta.sim)^2
  ozone.mean2 <- colMeans(ozone.sim2, na.rm = TRUE)
  
  ozone.pred.mean.RGRND[iid] <- mean(ozone.mean2, na.rm = TRUE)
  ozone.pred.sd.RGRND[iid] <- sd(ozone.mean2, na.rm = TRUE)
  ozone.pred.IQR.RGRND[iid] <- IQR(ozone.mean2, na.rm = TRUE)
  
  # observed ozone
  
  st.sub2 <- subset(st.sub, st.sub$year<2005)
  ozone.obs.mean[iid] <- mean(st.sub2$ozone, na.rm = TRUE)
  ozone.obs.sd[iid] <- sd(st.sub2$ozone, na.rm = TRUE)
  ozone.obs.IQR[iid] <- IQR(st.sub2$ozone, na.rm = TRUE)
}

##### Future projection

# merge historical VOC and NOx to future dataset

ft <- future
ft$hist.date <- paste((as.numeric(format(ft$date, "%Y"))-50), format(ft$date,"%m-%d"), sep="-") 
ft$hist.date <- as.Date(as.character(ft$hist.date), format("%Y-%m-%d"))

st0 <- st[c(1,2,31:36,42:44)]
colnames(st0)[2] <- "hist.date"
st0 <- st0[order(st0$siteID, st0$hist.date),]
ft <- ft[order(ft$siteID, ft$hist.date),]
ftr <- merge(st0, ft, by=c("siteID", "hist.date")) 

ftr$stemp.max45 <- ftr$temp.max45/sd(ftr$temp.max45, na.rm = TRUE)
ftr$shumid45 <- ftr$humid45/sd(ftr$humid45, na.rm = TRUE)
ftr$sprcp45 <- ftr$prcp45/sd(ftr$prcp45, na.rm = TRUE)
ftr$ssolar.GSW45 <- ftr$solar.GSW45/sd(ftr$solar.GSW45, na.rm = TRUE)
ftr$ssolar.RGRND45 <- ftr$solar.RGRND45/sd(ftr$solar.RGRND45, na.rm = TRUE)

ftr$stemp.max85 <- ftr$temp.max85/sd(ftr$temp.max85, na.rm = TRUE)
ftr$shumid85 <- ftr$humid85/sd(ftr$humid85, na.rm = TRUE)
ftr$sprcp85 <- ftr$prcp85/sd(ftr$prcp85, na.rm = TRUE)
ftr$ssolar.GSW85 <- ftr$solar.GSW85/sd(ftr$solar.GSW85, na.rm = TRUE)
ftr$ssolar.RGRND85 <- ftr$solar.RGRND85/sd(ftr$solar.RGRND85, na.rm = TRUE)

# projection by monitor

tmp.id <- unique(ftr$siteID)

ozone.pred.mean.GSW45 <- 0
ozone.pred.sd.GSW45 <- 0
ozone.pred.IQR.GSW45 <- 0

ozone.pred.mean.RGRND45 <- 0
ozone.pred.sd.RGRND45 <- 0
ozone.pred.IQR.RGRND45 <- 0

ozone.pred.mean.GSW85 <- 0
ozone.pred.sd.GSW85 <- 0
ozone.pred.IQR.GSW85 <- 0

ozone.pred.mean.RGRND85 <- 0
ozone.pred.sd.RGRND85 <- 0
ozone.pred.IQR.RGRND85 <- 0

for (iid in tmp.id){
  ftr.sub <- ftr[ftr$siteID == iid, ]
  fit0 <- lm(y~(sprcp+stemp.max+shumid)*sNOx+
               (ssolar+stemp.max+shumid)*N2+
               (ssolar+stemp.max+shumid)*(sNOx:Vl), data=ftr.sub)
  
  beta <- fit0$coef
  vcov <- vcov(fit0)
  beta.sim <- t(mvrnorm(10000, beta, vcov))
  
  # design matrix
  # (1) solar radiation GSW (RCP 4.5)
  fit1 <- lm(y~(sprcp45+stemp.max45+shumid45)*sNOx+
               (ssolar.GSW45+stemp.max45+shumid45)*N2+
               (ssolar.GSW45+stemp.max45+shumid45)*(sNOx:Vl), data=ftr.sub)
  x1 <- model.matrix(fit1)
  rownames(x1) <- NULL
  
  # (2) solar radiation RGRND (RCP 4.5)
  fit2 <- lm(y~(sprcp45+stemp.max45+shumid45)*sNOx+
               (ssolar.RGRND45+stemp.max45+shumid45)*N2+
               (ssolar.RGRND45+stemp.max45+shumid45)*(sNOx:Vl), data=ftr.sub)
  x2 <- model.matrix(fit2)
  rownames(x2) <- NULL
  
  # (3) solar radiation GSW (RCP 8.5)
  fit3 <- lm(y~(sprcp85+stemp.max85+shumid85)*sNOx+
               (ssolar.GSW85+stemp.max85+shumid85)*N2+
               (ssolar.GSW85+stemp.max85+shumid85)*(sNOx:Vl), data=ftr.sub)
  x3 <- model.matrix(fit3)
  rownames(x3) <- NULL
  
  # (4) solar radiation RGRND (RCP 8.5)
  fit4 <- lm(y~(sprcp85+stemp.max85+shumid85)*sNOx+
               (ssolar.RGRND85+stemp.max85+shumid85)*N2+
               (ssolar.RGRND85+stemp.max85+shumid85)*(sNOx:Vl), data=ftr.sub)
  x4 <- model.matrix(fit4)
  rownames(x4) <- NULL
  
  # predicted ozone -- future
  # (1) solar radiation GSW (RCP 4.5)
  ozone.sim1 <- (x1 %*% beta.sim)^2
  ozone.mean1 <- colMeans(ozone.sim1, na.rm = TRUE)
  
  ozone.pred.mean.GSW45[iid] <- mean(ozone.mean1, na.rm = TRUE)
  ozone.pred.sd.GSW45[iid] <- sd(ozone.mean1, na.rm = TRUE)
  ozone.pred.IQR.GSW45[iid] <- IQR(ozone.mean1, na.rm = TRUE)
  
  # (2) solar radiation RGRND (RCP 4.5)
  ozone.sim2 <- (x2 %*% beta.sim)^2
  ozone.mean2 <- colMeans(ozone.sim2, na.rm = TRUE)
  
  ozone.pred.mean.RGRND45[iid] <- mean(ozone.mean2, na.rm = TRUE)
  ozone.pred.sd.RGRND45[iid] <- sd(ozone.mean2, na.rm = TRUE)
  ozone.pred.IQR.RGRND45[iid] <- IQR(ozone.mean2, na.rm = TRUE)
  
  # (3) solar radiation GSW (RCP 8.5)
  ozone.sim3 <- (x3 %*% beta.sim)^2
  ozone.mean3 <- colMeans(ozone.sim3, na.rm = TRUE)
  
  ozone.pred.mean.GSW85[iid] <- mean(ozone.mean3, na.rm = TRUE)
  ozone.pred.sd.GSW85[iid] <- sd(ozone.mean3, na.rm = TRUE)
  ozone.pred.IQR.GSW85[iid] <- IQR(ozone.mean3, na.rm = TRUE)
  
  # (2) solar radiation RGRND (RCP 8.5)
  ozone.sim4 <- (x4 %*% beta.sim)^2
  ozone.mean4 <- colMeans(ozone.sim4, na.rm = TRUE)
  
  ozone.pred.mean.RGRND85[iid] <- mean(ozone.mean4, na.rm = TRUE)
  ozone.pred.sd.RGRND85[iid] <- sd(ozone.mean4, na.rm = TRUE)
  ozone.pred.IQR.RGRND85[iid] <- IQR(ozone.mean4, na.rm = TRUE)
}

```

### Historical
####  1. observed ozone
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
# mean
ozone.obs.mean
ozone.obs.sd
ozone.obs.IQR
```

####  2.1 predicted ozone -- GSW solar radiation
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.GSW
ozone.pred.sd.GSW
ozone.pred.IQR.GSW
```

####  2.2 predicted ozone -- RGRND solar radiation
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.RGRND
ozone.pred.sd.RGRND
ozone.pred.IQR.RGRND
```

### Future
####  3.1 predicted ozone -- GSW solar radiation (RCP 4.5)
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.GSW45
ozone.pred.sd.GSW45
ozone.pred.IQR.GSW45
```

####  3.2 predicted ozone -- RGRND solar radiation (RCP 4.5)
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.RGRND45
ozone.pred.sd.RGRND45
ozone.pred.IQR.RGRND45
```

####  3.1 predicted ozone -- GSW solar radiation (RCP 8.5)
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.GSW85
ozone.pred.sd.GSW85
ozone.pred.IQR.GSW85
```

####  3.1 predicted ozone -- RGRND solar radiation (RCP 8.5)
```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ozone.pred.mean.RGRND85
ozone.pred.sd.RGRND85
ozone.pred.IQR.RGRND85
```